# DigitalOcean App Platform Specification
#
# Deploy with: doctl apps create --spec .do/app.yaml
# Update with: doctl apps update YOUR_APP_ID --spec .do/app.yaml
#
# Or use the DigitalOcean dashboard and import this file.
# =============================================================================

name: ace-governance-platform

# Region - choose closest to your clients
region: nyc

# =============================================================================
# Services
# =============================================================================
services:
  - name: api
    # Use Dockerfile
    dockerfile_path: server/Dockerfile
    source_dir: /

    # GitHub integration (configure in dashboard)
    github:
      repo: YOUR_GITHUB_USERNAME/ace-governance
      branch: main
      deploy_on_push: true

    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/month, upgrade as needed

    # HTTP configuration
    http_port: 3001

    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME

      - key: COMPLIANCE_LEVEL
        value: production
        scope: RUN_TIME

      - key: LOG_LEVEL
        value: WARN
        scope: RUN_TIME

      - key: PORT
        value: "3001"
        scope: RUN_TIME

      - key: JWT_SECRET
        type: SECRET
        scope: RUN_TIME
        # Set in dashboard - generate with: openssl rand -hex 64

      - key: JWT_ISSUER
        value: ace-governance
        scope: RUN_TIME

      - key: JWT_AUDIENCE
        value: ace-platform
        scope: RUN_TIME

      - key: CORS_ORIGIN
        value: "${APP_URL}"
        scope: RUN_TIME
        # This auto-fills with your app's URL

      - key: POLICY_VERSION
        value: "2024.1.0"
        scope: RUN_TIME

      - key: ANTHROPIC_API_KEY
        type: SECRET
        scope: RUN_TIME
        # Set in dashboard

    # Routes
    routes:
      - path: /

    # Alerts (optional)
    alerts:
      - rule: DEPLOYMENT_FAILED
      - rule: DOMAIN_FAILED
      - rule: CPU_UTILIZATION
        value: 80
        operator: GREATER_THAN
        window: FIVE_MINUTES

# =============================================================================
# Domains (optional - configure your custom domain)
# =============================================================================
# domains:
#   - domain: api.your-domain.com
#     type: PRIMARY

# =============================================================================
# Databases (Phase 2 - uncomment when ready)
# =============================================================================
# databases:
#   - name: ace-db
#     engine: PG
#     production: true
#     cluster_name: ace-db-cluster
#     db_name: ace_governance
#     db_user: ace
